name = "lof-smart-monitor"
main = "lof-smart-monitor-worker.js"
compatibility_date = "2026-06-02"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = [
  "0 23 * * SUN-THU",  # 北京时间8:00 数据更新
  "0 10 * * 1-5",     # 北京时间18:00 数据更新
  "1-59/5 * * * 1-5"  # 交易时间每5分钟监控
]

[[kv_namespaces]]
binding = "FUNDS_KV"
id = "0d6d2904a8aa4a859e91292d1fd9f1e2"
